# Generated by Django 5.2.4 on 2025-08-25 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Remote', 'Remote')], max_length=50)),
                ('salary', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('', 'SELECT GENDER'), ('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('profile_photo', models.ImageField(upload_to='APPLICANT_PHOTOS/')),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('', 'CHOOSE STATES'), ('DL', 'Delhi'), ('MH', 'Maharashtra'), ('KA', 'Karnataka'), ('TN', 'Tamil Nadu'), ('UP', 'Uttar Pardesh')], max_length=2)),
                ('pincode', models.CharField(max_length=6)),
                ('higest_qualification', models.CharField(max_length=100)),
                ('university_name', models.CharField(max_length=150)),
                ('passing_year', models.IntegerField()),
                ('experience', models.DecimalField(decimal_places=1, max_digits=4)),
                ('last_company', models.CharField(blank=True, max_length=150, null=True)),
                ('skills', models.CharField(max_length=300)),
                ('resume', models.FileField(upload_to='APPLICANT_RESUMES/')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='JOBFORM.jobpost')),
            ],
        ),
    ]
