# Generated by Django 5.2.4 on 2025-08-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JOBFORM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='experience',
            field=models.FloatField(),
        ),
    ]
